### ISSUE TITLE
No nrepl on lollipop

### ISSUE THREAD

**Issue by rhg** [clojure-android/neko#40]
I got this to work on lollipop as the issue on clojure-android/clojure but nrepl doesn't start because when I try to connect I get a connection refused error. Is this just temporary or is this an issue? Here's my project.clj https://gist.github.com/rhg/b03df0b3c1f6bd92731f

**Comment by alexander-yakushev** [comment]
The dependencies look correct. I haven't yet tried Clojure on a Lollipop device but the emulator worked fine. Can you start by checking the emulator too?

Also, do you get any messages in `adb logcat` when you try to connect? Can you see `Nrepl started at port 9999` in logs when the application starts?

**Comment by rhg** [comment]
I tried it in a 4.4.2 emulator and it works I'll get a logcat later today.

**Comment by rhg** [comment]
When I start the app I do see the nrepl message, this must mean it's
failing before accepting the connection.

**Comment by alexander-yakushev** [comment]
So, no relevant log messages at the moment when you try to connect?

Also you are saying you tried with 4.4.2 emulator, can you please try with 5.0 one?

**Comment by rhg** [comment]
I predict it's throwing an exception, hopefully the log is useful.

**Comment by rhg** [comment]
This is weird, now it's working. And I was ruining lein clean beforehand.

**Comment by alexander-yakushev** [comment]
You mean, you ran `lein clean` even when the issue still existed?

**Comment by rhg** [comment]
Yes, I was using lein do clean, droid doall.

**Comment by alexander-yakushev** [comment]
Strange. Anyway, good it works now.

**Comment by rhg** [comment]
Well I did restart my device yesterday after filling this issue. Great work
BTW.

**Comment by alexander-yakushev** [comment]
Thank you! I will close this for now. Feel free to reopen if you get the same issue again.
