### ISSUE TITLE
Add web-view example

### ISSUE THREAD

**Issue by yamafaktory** [clojure-android/neko#43]
Hi,

First of all, thanks a lot for your work! I'm currently playing with the combo lein-droid/neko and I think that it could be awesome to have some more examples (like how to interact with a web-view in a layout. I looked at the documentation and there https://github.com/sattvik/Clojure-Android-Examples/blob/master/basic/src/clojure/com/sattvik/android/clojure/basic/ClojureBrowser.clj, but the latter seems to be outdated).

**Comment by alexander-yakushev** [comment]
Indeed those examples are quite old. You can rewrite that example using Neko by following this guide https://github.com/clojure-android/neko/wiki/User-interface . Buy I agree that having more examples will be helpful.

**Comment by yamafaktory** [comment]
Thank you @alexander-yakushev !
