### ISSUE TITLE
One of the recent changes in 4.0 breaks compilation

### ISSUE THREAD

**Issue by Malabarba** [clojure-android/neko#56]
About a week ago I could run `lein droid jar` on the 4.0 branch just fine, but today I tried again after pulling and got this:

    /home/artur/Git-Projects/neko/src/java/neko/App.java:17: error: cannot find symbol
            DalvikDynamicClassLoader.setContext(this);
                                    ^
      symbol:   method setContext(App)
      location: class DalvikDynamicClassLoader

**Comment by alexander-yakushev** [comment]
Major things have changed in 4.0 branch. Couple of things you have to do:
- depend on the latest version of Clojure: `[org.clojure-android/clojure "1.7.0-beta3-r2"]`
- look at the latest [sample](https://github.com/clojure-android/lein-droid/tree/master/sample), particularly the manifest (application should now be `neko.App`, also the updated defactivity syntax). This isn't needed to build Neko, of course, but is important when you use it later.

**Comment by Malabarba** [comment]
Are these tips are related to compiling neko or my app? I meant that I can't `jar` neko itself.

**Comment by Malabarba** [comment]
Oh, nevermind. Indeed the first tip fixed neko compilation. Thanks.
