### ISSUE TITLE
onClickListener not finding functions in the same namespace?

### ISSUE THREAD

**Issue by Agendine** [clojure-android/neko#61]
It's possible that I've done something wonky, but I have image-buttons being defined in an adapter for a GridView, and for the most part working properly.  However, calling a function defined elsewhere in the same file in the onClick procedure is causing "java.lang.RuntimeException: Unable to resolve symbol: <function-name> in this context, compiling:(NO_SOURCE_PATH:0:0)" errors, even though the same exact call can be run, successfully, in the REPL.

In fact, what it's doing is looking up an entry in a predefined map, 'function-name, and eval-ing that to call function-name, which it isn't finding.  Am I missing something here, or is the onClickListener having issues with either the scope or the quoting somehow?

**Comment by alexander-yakushev** [comment]
I'd rather see a sample code of what you are doing. But in any case, using eval in your application is a bad sign.

**Comment by Agendine** [comment]
Certainly!  And, of course, pilot error is a definite possibility here. 

So at the moment I have a :grid-view in the main activity, populated by an imagebutton adapter, like so:

![screen shot 2016-02-04 at 12 26 08 pm](https://cloud.githubusercontent.com/assets/9093414/12823575/c6902c30-cb3a-11e5-8e83-aeb0e9d9454f.png)

ID's are currently 3000 + cell#, just to label them programatically and avoid conflicts.  I'm sure there's probably a better way to do that than what I'm doing, but it does work.  The update-fn isn't currently being used to do anything. 

display-moves is then just directly setting the imageDrawable for image-buttons in-place.
![screen shot 2016-02-04 at 12 27 29 pm](https://cloud.githubusercontent.com/assets/9093414/12823587/d4251b4e-cb3a-11e5-8d52-52b787f702a5.png)


![screen shot 2016-02-04 at 11 36 37 am](https://cloud.githubusercontent.com/assets/9093414/12821986/cea7dffa-cb33-11e5-97b8-f3ab135659ce.png)

Wherein the (get-in game [:board x y :type]) is pulling from a singleton property map for each piece-type in the game, such as:
![screen shot 2016-02-04 at 11 37 05 am](https://cloud.githubusercontent.com/assets/9093414/12821996/da881934-cb33-11e5-8eb7-b1731a9337eb.png)


and move-forward, etc, are just producing a vector of [x y] pairs for available moves.

As said, `(display-moves (*a) 3)` does work as it should from the repl, but the same command from the onClick produces "Unable to resolve symbol: move-forward".

(on clicking a piece)
![screen shot 2016-02-02 at 11 21 55 pm](https://cloud.githubusercontent.com/assets/9093414/12823604/edfad414-cb3a-11e5-89b7-5a410d375405.png)



Sorry if I've given more info than strictly relevant, but I do appreciate the extra eyes. Neko's been great to me so far, but I'm still wrapping my head around it.

**Comment by alexander-yakushev** [comment]
OK, so here's the problem: you don't store functions in your singleton map, but mere symbols. Then you try to resolve those symbols using eval, but since that may be called in some other namespace, the functions then can't be resolved.

In Clojure we don't do that. Instead, you put actual functions inside your map:

```clojure
{:moves [[move-horizontal 1]
         [move-forward 1] ...
```

And then you don't use `eval` when calling the function:
```clojure
(fn [[move-function num-spaces]]
  (move-function (get game :board) num-spaces ...
```

Problem solved! :)

**Comment by alexander-yakushev** [comment]
Looks you are doing an awesome project, by the way!

**Comment by Agendine** [comment]
Thanks so much, for both the help and the kind words.  I'm kicking myself that I didn't see the problem sooner.  Still a goodly ways to go, but if you'd like I'll shoot you an email when it's done!

**Comment by alexander-yakushev** [comment]
Yes, absolutely! I'd love to see this finished.

A few more notes. You can actually save not the function objects in the
map, but their Vars.

```
#'move-forward 1
...
```

This way you won't have to reload the map every time toy redefine the
function. It will have one extra layer of indirection like you had with
symbols, but without eval.

You can also just use multimethods. It's rarely needed to implement this
kind of dispatching manually.

**Comment by Agendine** [comment]
After doing some reading, I've realized you're completely right: multimethods are a much more idiomatic way of handling things, and I think I'm going to chart out some refactoring based on that.

However, I'm still not 100% sure there isn't some weirdness going on with the onClick functionality.
For example,

```clojure
(.setOnClickListener image-button
    (proxy [android.view.View$OnClickListener] []
        (onClick [v]
            (display-hl-pos activity 0)
```

works, as does

```clojure
(.setOnClickListener image-button
    (proxy [android.view.View$OnClickListener] []
        (onClick [v]
            (do
                (display-hl-pos activity 0)
                (display-hl-pos activity 8)
                (display-hl-pos activity 72)
                (display-hl-pos activity 80)))))
```

and

```clojure
(map (fn [pos] (display-hl-pos (*a) pos)) [0 8 72 80]))
```

in the REPL.

But putting in 
```clojure
(.setOnClickListener image-button
    (proxy [android.view.View$OnClickListener] []
        (onClick [v]
            (map (fn [pos] (display-hl-pos (*a) pos)) [0 8 72 80]))))
```

to the image-button definition causes nothing to happen.

I've worked around this by another method, but it seems odd that mapping would fail when the same operation called explicitly succeeds.

**Comment by alexander-yakushev** [comment]
map is lazy, and since you are not using it's return value anywhere it
might not be executed at all. Try wrapping it in doall, or replace with
mapv.

**Comment by Agendine** [comment]
Aaaaaaah.  It all makes sense now.  Once again, thank you.

**Comment by alexander-yakushev** [comment]
No problem!
